on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: CI
env:
  CARGO_TERM_COLOR: always
  HOST: x86_64-unknown-linux-gnu
  RUSTFLAGS: "-D warnings"
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: {profile: minimal, toolchain: '${{ matrix.rust }}', override: true}
      - run: cargo test
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [beta]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: {profile: minimal, toolchain: '${{ matrix.rust }}', override: true, components: clippy}
      - run: cargo clippy
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
